version: 2.1
orbs:
    hello: circleci/hello-build@0.0.5


commands:
  print_pipeline_id:
    description: "A very simple command for demonstration purposes"
    steps:
      - run: echo $CIRCLE_WORKFLOW_ID

jobs:
  hello :
    docker:
      - image: circleci/node:13.8.0 
    steps:
      - print_pipeline_id 

workflows:
    "Hello Workflow":
        jobs:
          - hello